"""create query reports

Revision ID: 1bf10179c3a5
Revises: d87b22e880c0
Create Date: 2026-05-08 12:56:43.358454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf10179c3a5'
down_revision: Union[str, Sequence[str], None] = 'd87b22e880c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('analyst_output_json', sa.Text(), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=False),
    sa.Column('hero_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_reports')
    # ### end Alembic commands ###
