"""create scrape and hero stats tables

Revision ID: d87b22e880c0
Revises: 
Create Date: 2026-03-30 20:35:54.172316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87b22e880c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_for_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('hero_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scrape_run_id', sa.String(), nullable=False),
    sa.Column('hero', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('lane', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('ban_rate', sa.Float(), nullable=True),
    sa.Column('pick_rate', sa.Float(), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_stats')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
